### ISSUE TITLE
npm audit reports lots of issues after installing ol3-layerswitcher

### ISSUE THREAD

**Issue by woodbri** [walkermatt/ol3-layerswitcher#1]
npm audit

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  High            Denial of Service

  Package         ws

  Patched in      >= 1.1.5 <2.0.0 || >=3.3.1

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  engine.io > ws

  More info       https://nodesecurity.io/advisories/550

  High            Denial of Service

  Package         ws

  Patched in      >= 1.1.5 <2.0.0 || >=3.3.1

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  socket.io-client > engine.io-client > ws

  More info       https://nodesecurity.io/advisories/550

  High            DoS due to excessively large websocket message

  Package         ws

  Patched in      >=1.1.1

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  engine.io > ws

  More info       https://nodesecurity.io/advisories/120

  High            DoS due to excessively large websocket message

  Package         ws

  Patched in      >=1.1.1

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  socket.io-client > engine.io-client > ws

  More info       https://nodesecurity.io/advisories/120

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > send > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  engine.io > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  socket.io-adapter > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  socket.io-client > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  socket.io-client > engine.io-client > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  socket.io-client > socket.io-parser > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  socket.io-parser > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  socket.io-adapter > socket.io-parser > debug

  More info       https://nodesecurity.io/advisories/534

  High            Sanitization bypass using HTML Entities

  Package         marked

  Patched in      >=0.3.6

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > marked

  More info       https://nodesecurity.io/advisories/101

  High            Regular Expression Denial of Service

  Package         marked

  Patched in      >=0.3.9

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > marked

  More info       https://nodesecurity.io/advisories/531

  Critical        Symlink Arbitrary File Overwrite

  Package         tar

  Patched in      >=2.0.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > get-down >
                  tar

  More info       https://nodesecurity.io/advisories/57

  Moderate        Prototype pollution

  Package         hoek

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > get-down >
                  request > hawk > boom > hoek

  More info       https://nodesecurity.io/advisories/566

  Moderate        Prototype pollution

  Package         hoek

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > get-down >
                  request > hawk > cryptiles > boom > hoek

  More info       https://nodesecurity.io/advisories/566

  Moderate        Prototype pollution

  Package         hoek

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > get-down >
                  request > hawk > hoek

  More info       https://nodesecurity.io/advisories/566

  Moderate        Prototype pollution

  Package         hoek

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > get-down >
                  request > hawk > sntp > hoek

  More info       https://nodesecurity.io/advisories/566

  High            Downloads Resources over HTTP

  Package         closure-util

  Patched in      No patch available

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util

  More info       https://nodesecurity.io/advisories/165

  High            Regular Expression Denial of Service

  Package         fresh

  Patched in      >= 0.5.2

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > send > fresh

  More info       https://nodesecurity.io/advisories/526

  High            Regular Expression Denial of Service

  Package         negotiator

  Patched in      >= 0.6.1

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  engine.io > accepts > negotiator

  More info       https://nodesecurity.io/advisories/106

  High            Regular Expression Denial of Service

  Package         parsejson

  Patched in      No patch available

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > socket.io >
                  socket.io-client > engine.io-client > parsejson

  More info       https://nodesecurity.io/advisories/528

  High            Regular Expression Denial of Service

  Package         minimatch

  Patched in      >=3.0.2

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > metalsmith >
                  recursive-readdir > minimatch

  More info       https://nodesecurity.io/advisories/118

  Moderate        Memory Exposure

  Package         tunnel-agent

  Patched in      >=0.6.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > get-down >
                  request > tunnel-agent

  More info       https://nodesecurity.io/advisories/598

  Moderate        Remote Memory Exposure

  Package         request

  Patched in      >=2.68.0

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > get-down >
                  request

  More info       https://nodesecurity.io/advisories/309

  Moderate        Regular Expression Denial of Service

  Package         mime

  Patched in      >= 1.4.1 < 2.0.0 || >= 2.0.3

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > send > mime

  More info       https://nodesecurity.io/advisories/535

  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   ol3-layerswitcher

  Path            ol3-layerswitcher > openlayers > closure-util > lodash

  More info       https://nodesecurity.io/advisories/577

found 29 vulnerabilities (10 low, 7 moderate, 11 high, 1 critical) in 1688 scanned packages
  29 vulnerabilities require manual review. See the full report for details.

**Comment by walkermatt** [comment]
Thanks for reporting. This package and repo are now deprecated in favour of ol-layerswitcher which depends on the newer ol package.

It looks like the vulnerabilities are with various dependencies of the openlayers package.

**Comment by jonyeezs** [comment]
Would love some guidance, if there's any breaking changes, on migrating to **ol-layerswitcher**.

If none, do respond here as well :bowing_man:

**Comment by walkermatt** [comment]
@jonyeezs Hi no breaking changes you should be fine moving over to [ol-layerswitcher](https://github.com/walkermatt/ol-layerswitcher) but see the [note in the README](https://github.com/walkermatt/ol-layerswitcher#parcel-webpack-etc) if you've been using the `ol` package.
