### ISSUE TITLE
Control Layer Opacity

### ISSUE THREAD

**Issue by felipe84** [walkermatt/ol3-layerswitcher#11]
Thanks for implementing the layerswitcher. 

How can I have an opacity slider using the layerswitcher as the following OL3 example? http://openlayers.org/en/v3.2.1/examples/layer-group.html

I hope what I have requested is possible. 
Thanks again.

**Comment by walkermatt** [comment]
@felipe84 It should be possible by overriding the `renderLayer_` method but it's not a feature that I'm inclined to add at the moment.

Cheers,

Matt.

**Comment by felipe84** [comment]
Thanks for tour reply. 
Please if you have any tip or roadmap in order to implement it let me know because I'm a begginer in programming language.
