### ISSUE TITLE
Consider Publishing on jsdelivr CDN

### ISSUE THREAD

**Issue by kpurdon** [walkermatt/ol3-layerswitcher#13]
This would allow users to easily include you library with simple HTML.

> Similar to Google Hosted Libraries, jsDelivr is an open source CDN that allows developers to host their own projects and anyone to link to our hosted files in their websites.

http://www.jsdelivr.com/
https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

I would be happy to do the necessary work if your interested.

**Comment by walkermatt** [comment]
I'd be open to this especially as we're already tagging for Bower.

**Comment by kpurdon** [comment]
I actually just found rawgit.com. For example here are the URLS:

https://cdn.rawgit.com/walkermatt/ol3-layerswitcher/v1.0.2/src/ol3-layerswitcher.js
https://cdn.rawgit.com/walkermatt/ol3-layerswitcher/v1.0.2/src/ol3-layerswitcher.css

It might be nice to add this information to the README.

**Comment by walkermatt** [comment]
I've not used cdn.rawgit.com but it looks as though it provides an equivalent service to jsdelivr.com providing the repo contains tags (which ours does). There is a fairly prominent warning regarding availability at rawgit.com but I guess the same applies to both.

**Comment by walkermatt** [comment]
Now available here: http://www.jsdelivr.com/projects/openlayers.layerswitcher
