### ISSUE TITLE
Reverse order of layers.

### ISSUE THREAD

**Issue by drupol** [walkermatt/ol3-layerswitcher#14]
Hello,

Why is the order of group reverted from its declaration ?

In the example you declare the Base maps group, then the Overlays group, but in the rendered map, it's first the Overlays then the Base maps group that are displayed in that order.

Would it be better to display them in the natural order of their declaration ?

**Comment by walkermatt** [comment]
@drupol Hi, the intention is to display the layers in the draw order from a users perspective (overlays displayed at the top, base mapping below)

**Comment by drupol** [comment]
Oh ok ! thanks for the explanation. In the meantime, I made a system in Drupal to allow users to reorder them as they want.

![openlayers-ol4-layerswitcher](https://cloud.githubusercontent.com/assets/252042/8860253/e0361426-3182-11e5-9861-4c1aefc816d3.jpg)

Thanks for your fast answer !

**Comment by walkermatt** [comment]
Sweet, glad you where able to use the layer switcher :smile:

**Comment by drupol** [comment]
I'll post a link to the demo when it's done :)

**Comment by drupol** [comment]
Here it is: http://dev.through-my-eyes.be/openlayers_examples/openlayers_examples_map_ol3layerswitcher
