### ISSUE TITLE
Vertical Scrollbar

### ISSUE THREAD

**Issue by 1Map** [walkermatt/ol3-layerswitcher#18]
If we have a lot of layers the layer control's height is more than that of the map and the layer control cannot be scrolled down.  Do you maybe have an example of how this can be achieved?

**Comment by walkermatt** [comment]
I've only briefly looked at this but it should be possible via CSS. Try something like:

    /* Make the main content element stretch
       to near the bottom of the map window */
    .layer-switcher {
        bottom: 2.5em;
    }

    /* Avoid the panel from growing taller than it's container and apply
       scrollbars if needed */
    .layer-switcher .panel {
        max-height: 100%;
        overflow: auto;
    }

If you settle on a solution then let me know as I'd be happy to consider a pull request.

**Comment by debaser75** [comment]
Thanks for the LayerSwitcher, Matt!  I've got this scrolling behavior working on Desktop (Chrome and Edge on Windows), but I cannot scroll on Android devices using both Chrome and Firefox.  I started the OL3 project using Boundless's Web App Builder (it looks like they've incorporated your LS in it!).  Then tried to implement your suggestions.  That did work on desktop, but not mobile.  Then I downloaded your code and examples and made the css changes that you suggested.  I added the "countries" layer multiple times and named them counties2, countries3, etc to create a long list of layers in the LS so it'd exceed the screen on my mobile.  Again, the scrolling works on desktop, but not on mobile.  Any ideas?

Thanks again for your contribution!

**Comment by walkermatt** [comment]
@debaser75 it's possible that we need something like this https://github.com/walkermatt/ol3-popup/blob/master/src/ol3-popup.js#L149 to handle scrolling on touch devices.

**Comment by debaser75** [comment]
Thanks.  I got the scrolling to work on Chrome and Firefox on Android using the css below.  But I tried adding it to the LS that gets created by Boundless's "Web App Builder" and it didn't work.  So there's progress, but I'm not of of the weeds yet.  But I thought I'd post this so others could use it.  The key was "position: relative"

.layer-switcher {
    position: absolute;
    top: 3.5em;
    right: 0.5em;
    text-align: left;
    bottom: 2.5em;
   
}

.layer-switcher .panel {
    padding-right: 50px;
    border: 1px solid #cccccc;
    background-color: white;
    margin: 0;
    display: none;
    position: relative;
     max-height: 100%;
    overflow: scroll;
}

**Comment by walkermatt** [comment]
@debaser75 Thanks for looking into this further. Can you post a link to the code for the layer switcher generated by the Boundless Web App Builder. I'm not entirely sure they are using this layer switcher.

**Comment by debaser75** [comment]
Matt, I'm sorry for the delayed response.  The holidays happened and then a lot kayaking and then a job application.  The source code generated by the Boundless Web App Builder has comments that explicitly state that their layer switcher is based on your code.  You can download an entire web app generated by their builder here: https://goo.gl/uJ7Hex

**Comment by walkermatt** [comment]
Sounds like fun ☺. Thanks I'll take a look.

I've been working on a solution which I'll push to a separate branch once I'm happy.

**Comment by walkermatt** [comment]
I've pushed my work on making the panel scrollable to a [scroll branch](https://github.com/walkermatt/ol3-layerswitcher/tree/scroll), demo on rawgit.com: http://rawgit.com/walkermatt/ol3-layerswitcher/scroll/examples/scroll.html

The main changes are:
* The panel now displays a vertical scrollbar if required.
* The button is no longer displayed when the panel is shown to simplify layout when a scrollbar is shown.

There are two CSS properties that affect the height of the panel and hence scrolling:

Setting the bottom for the control ensures the panel will be contained by the map and not overlap the attribution control at the bottom of the map by default (see [src/ol3-layerswitcher.css](https://github.com/walkermatt/ol3-layerswitcher/blob/scroll/src/ol3-layerswitcher.css#L17)):

    .layer-switcher.shown {
        bottom: 3em;
    }

You can also set a `max-height` to further constrain the height if required (see [examples/scroll.css](https://github.com/walkermatt/ol3-layerswitcher/blob/scroll/examples/scroll.css#L3)):

    .layer-switcher.shown {
        max-height: 170px;
    }

/cc @1Map, @ThomasG77. @michogar, @jfrankl  any feedback / testing appreciated.
