### ISSUE TITLE
Example not working due to mixed SSL content

### ISSUE THREAD

**Issue by stephankn** [walkermatt/ol3-layerswitcher#21]
example fails when rawgit is loaded as https. This is due to trying to load openlayers as http.

Unfortunately OpenLayers is not served as https. So I propose to also host the openlayers css and js code as a copy and use a protocol independent URL in the example..

**Comment by holimatic** [comment]
Hi
Instead of using openlayer.js you can use
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/ol3/3.13.1/ol.min.js"></script>
for https:

**Comment by walkermatt** [comment]
@holimatic thanks, I've chosen to simply load ol3 via https after reading the update here: http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by walkermatt** [comment]
The demo WMS overlay from @boundlessgeo is only available under plain http so you still get some mixed content warnings if accessing the examples via https://rawgit.com/ but I think I can live with that for now.
