### ISSUE TITLE
Google layer with ol3-google-maps doesn't get radio button.

### ISSUE THREAD

**Issue by fipp** [walkermatt/ol3-layerswitcher#22]
Hi! This issue was posted first here: https://github.com/mapgears/ol3-google-maps/issues/37. But after some thought I concluded that this is perhaps more of an ol3-layerswitcher question? Anyone. here it is:

Has anyone here used `ol3-layerswitcher` together with `ol3-google-maps`? For some reason the google layer doesn't show correctly in my layer switcher:

<img width="323" alt="screen shot 2016-01-18 at 15 37 02" src="https://cloud.githubusercontent.com/assets/1716906/12393973/579ebce0-bdf9-11e5-9f1a-e79c3c63c43b.png">

Relevant pieces of code:
```
    var map = new ol.Map({
      target: 'map',
    });

    var googleLayer = new olgm.layer.Google({
      title: 'Kart (Google)',
      type: 'base',
    })
    map.addLayer(googleLayer);

    var shadedBing = new ol.layer.Tile({
      title: 'Kart (Bing)',
      type: 'base',
      source: new ol.source.BingMaps({
        key: bingKey,
        imagerySet: 'Road'
      })
    });
    map.addLayer(shadedBing);

    ...

    map.setView(new ol.View({
        projection: 'EPSG:900913',
        center: ol.proj.transform(
          settings.coords,
          'EPSG:4326',
          'EPSG:900913'
        ),
        zoom: 14
    }));

    var layerSwitcher = new ol.control.LayerSwitcher({});
    map.addControl(layerSwitcher);

    var olGM = new olgm.OLGoogleMaps({map: map});
    olGM.activate();

```

Any thoughts?

**Comment by walkermatt** [comment]
I'm pretty sure it's because `olgm.OLGoogleMaps` extends `ol.layer.Group`. I'll give it some thought...

**Comment by fipp** [comment]
Looks like you're right. I've created a jsfiddle here illustrating the problem: https://jsfiddle.net/penn/swn6q0vs/

In ol3-layerswitcher.js, if I make this change I get it to work:
```
- if (lyr.getLayers) {
+ if (lyr.getLayers && lyr.getLayers().length > 1) {
```

Meaning that the `getLayers` method of `lyr` has to return an non-empty array, otherwise `lyr` will be drawn as a simple layer, and not as a group. This change makes it work for me:

<img width="446" alt="screen shot 2016-01-19 at 09 21 32" src="https://cloud.githubusercontent.com/assets/1716906/12413332/5b679a8c-be8e-11e5-8f7b-69839e3fb60e.png">

However I'm pretty sure that this isn't exactly a good fix ... :)

**Comment by fipp** [comment]
So the issue at https://github.com/mapgears/ol3-google-maps/issues/37 has been further investigated, it's pretty much established that this is an ol3-google-maps issue. I guess there isn't any reason to discuss this matter further here, unless you have some suggestion on a smarter better way of hacking ol3-layerswitcher.js than the way I've described. If not, you can go ahead and close this issue :) Thanks for the help!

**Comment by walkermatt** [comment]
It's now possible to collapse a group so it's displayed as a regular layer, see #36.
