### ISSUE TITLE
My feature popup interrupts choosing a layer

### ISSUE THREAD

**Issue by fipp** [walkermatt/ol3-layerswitcher#23]
Hi!

Have a look at this video: https://v.usetapes.com/xQ94CHYuqE
Or this plunker: https://plnkr.co/edit/1DZhhT2SZFlGVCZJzeh7 

As you can see, the `map.forEachFeatureAtPixel()` call inside `map.on('pointermove', function (evt) { ... })` detect my feature and display the tooltip, even though I'm hovering over the above-laying div to choose a layer.

Any advice on how I best can avoid this, aka disabling my feature popup when choosing a layer?

**Comment by walkermatt** [comment]
Hi,

Looking at it briefly I'm not sure there is anything a control can do to avoid this behaviour as the `pointermove` event appears to be fired when the mouse is within the map regardless of any overlays or controls. Looking at the event object `evt` it looks like you might be able to use the `evt.browserEvent.target` property which appears to be a reference to the DOM element that the mouse is over when the event is fired. Something along the lines of only handling the event if `evt.browserEvent.target` is the map canvas.

Good luck!

Matt.

**Comment by fipp** [comment]
Inspired by your advice, I fixed it this way: When the `pointermove` listener callback finds a feature in the map, it will only show the feature tooltip if none of the ancestors of `evt.originalEvent.target` contains a class called `layer-switcher`.:

```
map.on('pointermove', function(evt) {
  var feature = map.forEachFeatureAtPixel(..);
- if ( feature ) {
+ if ( feature && jQuery(evt.originalEvent.target).parents('.layer-switcher').length === 0 ) {
   ...
  }
});
```

Because of some other overlays, it wasn't a good solution for me to only show tooltips when `evt.originalEvent.target` is the map canvas.

**Comment by walkermatt** [comment]
Great, glad you found a solution :smiley_cat:
