### ISSUE TITLE
More of a trivial issue..

### ISSUE THREAD

**Issue by johnrogers4** [walkermatt/ol3-layerswitcher#24]
Hey, I was just wondering if you knew how to set overlays to have a default setting of not being displayed on the map until they are selected, as in they are unchecked by default, if you get me. 

I have 4 overlays and they display on top of eachother, I'm new to openlayers and there's not a lot of people I can go to for advice, so I looked at your project and it seems to have what id like here but I'm not sure how you did it!

**Comment by walkermatt** [comment]
Hi John, if I understand you correctly I think you need to set the `visibility` property of the layer that you don't want to be shown by default to `false`. See [this example](https://github.com/walkermatt/ol3-layerswitcher/blob/master/examples/layerswitcher.js#L25).

**Comment by johnrogers4** [comment]
Hey Matt, thanks for the reply. I'm using a GML layer, with KML format. Is there a way to apply that visible property in this case? It seems the documentation for a lot of these layers aren't online anymore! Here's what I am using in my code anyway. 

```
 var  world = new OpenLayers.Layer.GML("Countries", "public_kml/Robert_Russell_Natural_Earth_Countries.kml", 
    {
        projection: new OpenLayers.Projection("EPSG:4326"),
        format: OpenLayers.Format.KML,
        formatOptions: {'extractStyles': false}
    });  
    map.addLayer(world);
`
```

**Comment by walkermatt** [comment]
I'm pretty sure the code you've posted is from OpenLayers 2. Quite a lot
changed in version 3, you can find an example of loading a KML source in
ol3 here: http://openlayers.org/en/v3.7.0/examples/kml.html.

To hide the layer in the KML example by default you need to add a `visible`
property with a value of `false` to the `ol.layer.Vector` options object.

**Comment by johnrogers4** [comment]
Thanks a lot Matt I got that sorted! I added setVisibility = false before adding it to the map. (I deleted the question bc I figured it out after I posted it!) 

If you don't mind I have one last question that is im trying to display the contents of user uploaded files onto the OpenStreetMap. So far I have a php file that takes the name, type and size of the user's file and stores it locally in a mysql database (with xampp). I'm pretty sure I need to store the path to the file somewhere now but I'm not sure how to go about it. If you have any pointers I'd be so greatful! If not its ok and thanks for your help

**Comment by walkermatt** [comment]
Cool, glad you've got it working :+1: 

I'd try https://gis.stackexchange.com/ for your other question. Be sure to include details of the format of the user data and maybe an expand on the use case (do you need to store the users data on your server or simply display it when it's uploaded for example?).
