### ISSUE TITLE
[feature] Visual hint for maps that are not visible because of min/max resolution

### ISSUE THREAD

**Issue by olivierdalang** [walkermatt/ol3-layerswitcher#25]
Hi !

It is very common to limit a layer to certain resolutions using their min/max resolution settings.

Layerswitcher doesn't take that into account, so that a layer that's not visible because of min/max resolution setting still appears in the layer list. This is very counter-intuitive.

I think that the layers that are not visible due to min/max resolution should either:
- A. not be displayed at all
- B. be grayed-out with a disabled checkbox, eventually with an icon making it obvious why the layer is hidden

I quickly implemented A : https://github.com/olivierdalang/ol3-layerswitcher/tree/show_only_if_visible
It's not finished :
- there's no option to choose between A or B, 
- I didn't think about how this should work with Base Layers
- I didn't investigate other types of invisibility (eg. outside of layer's bounds)

Thanks !!

**Comment by walkermatt** [comment]
Hi, I like the idea of option B, can you update one of the examples in your `show_only_if_visible` branch  so I can see it in action?

**Comment by walkermatt** [comment]
Implemented recently thanks to @RobertOrthofer 🎉
