### ISSUE TITLE
[feature] save layers visibilities

### ISSUE THREAD

**Issue by olivierdalang** [walkermatt/ol3-layerswitcher#26]
Hi !

In my application, I want the displayed layers to be saved across pages, so that the user doesn't have to repick all layers he wants to see. I guess it's a pretty common scenario.

I quickly implemented it using cookies, see here :

https://github.com/olivierdalang/ol3-layerswitcher/tree/visbility_in_cookie

It's not finished though :
- saving should be optional,
- currently there's no namespacing in the cookie, so that all maps of the same domain will share the same settings (conflicts if layers have the same title),
- another way to save the state is through the window hash, so that you can copy/paste a link

**Comment by walkermatt** [comment]
Hi, I think this should probably be done outside of the layer switcher. Sounds like you might have the start of a small map state library :smile:.
