### ISSUE TITLE
IIS and Geoserver

### ISSUE THREAD

**Issue by ismailrafi** [walkermatt/ol3-layerswitcher#27]
i want to access published layers through IIS but am facing the problem with REDIRECTING the URL

my domain on IIS is like this http://maps.icrisat.org
and the layers which i have published  using http://localhost:8080/geoserver/wms...

when open my website i will be selecting a link which points to geoserver layers using  javascript file in that i will be calling all layers but it is not displaying any layers but it is loading the base map.

someone can help me in this issue 

Thanks
Ismail

**Comment by walkermatt** [comment]
Hi, I think you might be better asking this question over at https://gis.stackexchange.com/ where someone might be able to help you with proxying the requests to GeoServer via IIS.
