### ISSUE TITLE
Button disappears when mouse over

### ISSUE THREAD

**Issue by holimatic** [walkermatt/ol3-layerswitcher#28]
Hi Matt
As I can see in the example your layerswitcher would exactly full fill my needs.
I implement according your example and the source javascript code of ol3-layerswitcher,js and ol3-layerswitcher.css in my website. My layer definition is according your addlayer,js. I wouldlike to have something similar like 'view the example on RawGit'. Unfortunately I get the button on the map but as soon as I move the mouse over the button, the button disappear and I'm not able to choose one of my defined layer. I guess something is missing but after two days of examination I couldn't find anything wrong.
Could help me or anybody else, or have a hint for me what's missing?
Cheers Guido

**Comment by walkermatt** [comment]
Can you post a link showing the issue? Also did you check the console in the dev tools in your browser to see if there are any errors shown?

**Comment by holimatic** [comment]
Thanks for replay.
Meanwhile I was able to solve the problem. I had to rename both files into ol3-layerswitch. css and ol3-layerswitch.js and it works now as expected. However I don't know why.
