### ISSUE TITLE
Add listener on selected layer

### ISSUE THREAD

**Issue by HamHamFonFon** [walkermatt/ol3-layerswitcher#30]
Hi,

First, thank you for your plugin, it's very usefull for my application :). 
I'm wondering if it's possible to add a feature getting the selected layer. I'm developping a plugin for drawing on a map and i need to know which layer to draw on it. 
Is-it possible to add an eventListener when the user select a layer by radio button and return the selected layer ?
Or I can try to develop it for my personnal use (or not ^^) but i'm not sure to do it in right way.

Thanks

(sorry for my bad english)

**Comment by walkermatt** [comment]
Hi, I don't think you need an event from the layer switcher for this as ol3 layers dispatch a `change:visible` event. Try something like the following to add an event listener to each layer in the map which simply logs the layer `title` and it's visibility:

    // Add a `change:visible` listener to all layers currently within the map
    ol.control.LayerSwitcher.forEachRecursive(map, function(l, idx, a) {
        l.on("change:visible", function(e) {
            var lyr = e.target;
            console.log(lyr.get('title'), lyr.getVisible());
        });
    });

[Details of the events dispatched by `ol.layer.Base`](http://openlayers.org/en/v3.13.0/apidoc/ol.layer.Base.html) and [docs for `ol.control.LayerSwitcher.forEachRecursive`](https://github.com/walkermatt/ol3-layerswitcher#static-olcontrollayerswitcherforeachrecursivelyrfn)

**Comment by HamHamFonFon** [comment]
Thank you for your answer, I try it and it's ok for me :).

**Comment by HamHamFonFon** [comment]
For example, here : https://github.com/HamHamFonFon/kurtogaphy/blob/master/public/src/openlayers.js line 129 :)
