### ISSUE TITLE
input element id at ol.control.LayerSwitcher.prototype.renderLayer_

### ISSUE THREAD

**Issue by vadp** [walkermatt/ol3-layerswitcher#31]
Currently generated input element id is mangled by idx parameter:
```var lyrId = lyr.get('title').replace(/\s+/g, '-') + '_' + idx;```

This doesn't work well is there are 2 maps with the same set of layers: in the 2nd map  ```label.htmlFor``` will refer to the input element of the 1st map as generated input element id is the same for the both maps.

This makes a funny effect: when you click at the label at the 2nd map it actually switches a layer at the 1st map.

A solution for this issue could look something like this:

```var lyrId = lyr.get('title').replace(/\s+/g, '-') + '_' + Math.floor(Math.random() * 1000000);```

**Comment by walkermatt** [comment]
Thanks for reporting this, I had a brief look this morning and have been able to reproduce. I'm going to add some tests then look at a fix along the lines you suggest :thumbsup:
