### ISSUE TITLE
Get and set actual layer type by ID or so

### ISSUE THREAD

**Issue by holimatic** [walkermatt/ol3-layerswitcher#33]
Hi Matt,

I've successfully implemented your layerswitcher.
However I would like to know how to get and set the actual layer using an ID or something else in order to save the actual layer type. I was not able to find anything. How is that possible?

Second question how can I checkmark automatically the overlay when I using sat view and back by select any other layer. Must be done by using visible but for me is not clear how do I implement it.
Thanks in advance for your feedback...
Cheers Guido

My layer definitions looks as follows:
```
      mapLayers = [
        new ol.layer.Group({
          title: 'Basemaps',
          layers: [
            new ol.layer.Tile({
              title: 'SatelliteView',
              type: 'base',
              visible: false,
              source: new ol.source.OSM({ url:'//server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'})
              //source: new ol.source.MapQuest({layer: 'sat'})
            }),
            new ol.layer.Tile({
              title: 'Topographic',
              type: 'base',
              visible: false,
              source: new ol.source.XYZ({attributions:[attribution],url:'//server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}'}),
            }),
            new ol.layer.Tile({
              title: 'EsriRoad',
              type: 'base',
              visible: false,
              source: new ol.source.XYZ({attributions:[attribution],url:'//server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}'}),
            }),
            new ol.layer.Tile({
              title: 'MapquestRoad',
              type: 'base',
              visible: true,
              source: new ol.source.MapQuest({layer: 'osm'}),
              //source: new ol.source.OSM({url:'//{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png'}),
            }),
          ],
        }), //End of basemaps
        new ol.layer.Group({
          title: 'Overlays',
          layers: [
            new ol.layer.Tile({
              title: 'Themes',
              visible: false,
              source: new ol.source.XYZ({attributions:[attribution],url:'//server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}'}),
            }),
          ],
        }), //End of overlays
      ]; //End of var mapLayers


```

**Comment by walkermatt** [comment]
Hi, this feels like a similar situation to #30 where I think the best approach may be to interact with the layer instances directly and listen to the appropriate events despatched by Details of the events dispatched by ol.layer.Base

**Comment by holimatic** [comment]
I'm able now to see the selected layer in the console but how do I set the overlays (Themes) to checked and back.
// Add a `change:visible` listener to all layers currently within the map
ol.control.LayerSwitcher.forEachRecursive(map, function(l, idx, a) {
  l.on("change:visible", function(e) {
    var lyr = e.target;
    if (lyr.getVisible() == true) {
      console.log(idx,' ',lyr.get('title'),lyr.getVisible());
      if (lyr.get('title') === 'SatelliteView') {
        console.log(idx,' Themes -> setVisible=true');
      }
      else {
        console.log(idx,' Themes -> setVisible=false');
      }
    }
  });
});
It should be done where is setVisible=true and false.
Any tips would be appreciated.

**Comment by holimatic** [comment]
`// Add a `change:visible` listener to all layers currently within the map
ol.control.LayerSwitcher.forEachRecursive(map, function(l, idx, a) {
  l.on("change:visible", function(e) {
    var lyr = e.target;
    if (lyr.getVisible() == true) {
      console.log(idx,' ',lyr.get('title'),lyr.getVisible());
      if (lyr.get('title') === 'SatelliteView') {
        console.log(idx,' Themes -> setVisible=true');
      }
      else {
        console.log(idx,' Themes -> setVisible=false');
      }
    }
  });
});
`

**Comment by holimatic** [comment]
Well, I get a solution don't if it's nice or not but it works.
First of all I separate the tile to ovlSubject
```
      var ovlSubject = new ol.layer.Tile({
        title: 'Subject',
        visible: false,
        source: new ol.source.XYZ({attributions:[attribution],url:'//server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',
          projection: 'EPSG:3857'
        })
      });

```
and then I could have access to this setVisible
```
      if (lyr.get('title') === 'SatelliteView') {
        ovlSubject.setVisible(true);
      }
      else if (idx > 0) {
        ovlSubject.setVisible(false);
      }

```
and finally I need to check if idx is > 0 because SatelliteView layer and ovlSubject has the same idx=0. However now it works for me, but as I said not sure if that is a correct solution or not.
