### ISSUE TITLE
Grouping base layers

### ISSUE THREAD

**Issue by Saurbaum** [walkermatt/ol3-layerswitcher#35]
The traditional way to produce a satellite map with roads in MapQuest is to make a sat layer and a road layer.

I can't seem to group these together in a single entry using layer switcher.  Either they appear as independent base layers or the roads would become an optional overlay (which makes the hybrid option redundant along side the satellite layer)

**Comment by walkermatt** [comment]
This also came up in #22, I'm wondering if we need the ability to say that a given layer group should be rendered as a layer.

**Comment by Saurbaum** [comment]
As a novice openlayers user I would say that makes sense to me as that was the first thing I tried to do.

**Comment by walkermatt** [comment]
Resolved by #36.
