### ISSUE TITLE
run code on switcer shown event

### ISSUE THREAD

**Issue by sadjehwty** [walkermatt/ol3-layerswitcher#40]
It's possible add handler to execute some code when switcher panel is shown?
I tried with
`$('.layer-switcher').mouseover(function () {
  setTimeout(function () { console.log('shown'); }, 10);
});`

but it isn't exactly the same thing

**Comment by walkermatt** [comment]
I'm wondering if we should be considering adding some events but in the meantime you could hook into either the `showPanel` or `renderPanel` methods something along the lines of:

    // Where `layerSwitcher` is an `ol.control.LayerSwitcher` instance
    layerSwitcher.renderPanel = function() {
        console.log('renderPanel');
        // Call the original renderPanel function passing the instance as `this`
        ol.control.LayerSwitcher.prototype.renderPanel.call(layerSwitcher)
    };
