### ISSUE TITLE
Internet Explorer problem

### ISSUE THREAD

**Issue by nformica** [walkermatt/ol3-layerswitcher#42]
It seems that layerswitcher does'nt work in MS Internet Explorer !
Do you confirm it ?

Cheers !
Nino

**Comment by walkermatt** [comment]
@nformica can you provide some more information please such as:

1.Are you saying that the [examples](https://github.com/walkermatt/ol3-layerswitcher#examples) don't work?
2. If so which version of IE?
3. Can you open the IE developer tools and tell me what's in the Console?

**Comment by nformica** [comment]
1. yes, examples don't work: layerswitcher panel appears, but you can not select layers (basemaps or overlays is the same)
2. IE 10 (10.0.9200.17609
3. In the console nothing ! No alert or error

**Comment by nformica** [comment]
@walkermatt I checked with IE 11 and  it's all right !

**Comment by walkermatt** [comment]
@nformica thanks for the info :+1: 

I suspect it might be an issue with ol3, the examples are using an old version of ol3 at the moment, I'll update and ping you to retest if that's OK?

**Comment by walkermatt** [comment]
I've updated the examples to use the latest ol3 release (3.17.1), would you mind testing again on IE 10?

**Comment by nformica** [comment]
@walkermatt 
I tested your updated examples with IE10, but the problem there's still !!
I attach a screen-record, so you can see what appens.

Anyway IMHO it's not important, because IE10 is  an older version !

**Comment by ThomasG77** [comment]
Maybe it's unrelated but try to add the script below (an excerpt from [simple example](http://openlayers.org/en/master/examples/simple.html))

```
<!-- The line below is only needed for old environments like Internet Explorer and Android 4.x -->
    <script src="http://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
```

**Comment by walkermatt** [comment]
@ThomasG77 thanks, I think that's got it. I've just updated the examples and tested on IE9 and IE11.
