### ISSUE TITLE
ol3-layerswitcher customization for Cesium.JS

### ISSUE THREAD

**Issue by thomasschmiedl** [walkermatt/ol3-layerswitcher#44]
I try to use ol3-layerswitcher in combination with Cesium.JS (example page: http://openlayers.org/ol3-cesium/examples/sidebyside.html). What customization is needed?

**Comment by walkermatt** [comment]
@thomasschmiedl have you tried adding the layerswitcher to that example?

I'd expect you would need to: 
* add the JS and CSS from `src` to [sidebyside.html](http://openlayers.org/ol3-cesium/examples/sidebyside.html)
* in [sidebyside.js](http://openlayers.org/ol3-cesium/examples/sidebyside.js)
    * add [`title`](https://github.com/walkermatt/ol3-layerswitcher/blob/master/examples/layerswitcher.js#L17) properties to each layer to show in the switcher and [`type: base`](https://github.com/walkermatt/ol3-layerswitcher/blob/master/examples/layerswitcher.js#L18)
    * create a layerswitcher instance and at it to the map (as shown in the [basic example](https://github.com/walkermatt/ol3-layerswitcher/blob/master/examples/layerswitcher.js#L64-L67))

Hope that helps.
