### ISSUE TITLE
When I deselect a Layer, it is only hides the CSS, but the layers is in RAM

### ISSUE THREAD

**Issue by homeandr777** [walkermatt/ol3-layerswitcher#45]
Hello,

where should I do layersxxxx.clear()?
For selected layers too? selectedlayers.clear();
So in which function do you hide css, there should be the layers cleaning from the ram,
Becouse if I deselect one layer, and I do Dragbox selection that deselceted layers comes in as selection.

With best regards

**Comment by walkermatt** [comment]
@homeandr777 when a layer is hidden by the switcher it's visibility is set via it's [`setVisible`](https://github.com/walkermatt/ol3-layerswitcher/blob/master/src/ol3-layerswitcher.js#L144) method.

Looking at the docs for [`ol.interaction.Select`](http://openlayers.org/en/latest/apidoc/ol.interaction.Select.html) it looks as thought only visible vector layers are queried providing the `layers` and `filter` options are not set.

**Comment by homeandr777** [comment]
http://openlayers.org/en/latest/apidoc/ol.interaction.DragBox.html

I am using DragBox selection, and I am working with geojson files, after selection of the layer, when I make selection with DragBox, and when I deselect the layer, all not selected features is gone, all selected features DragBOX with yellow color stayed.
Sadly  I can not upload pictures.
So I am using a variables for selected features with DragBox.



map.addInteraction(select_layer);

var geoselectedFeaturesstation_location = select_layer.getFeatures();

var dragBox = new ol.interaction.DragBox({
    condition: ol.events.condition.platformModifierKeyOnly
});
dragBox.setActive(true);

map.addInteraction(dragBox);

var selectedFeature = select_layer.getFeatures();

var dragedBox = function () {

    var extent = variabledragBox.getGeometry().getExtent();

    select_layer.forEachFeatureIntersectingExtent(extent, function (feature) {
        selectedFeature .push(feature);
      
    });
}

dragBox.on('boxend', dragedBox);

**Comment by homeandr777** [comment]
var select_layer;

select_layer= new ol.interaction.Select({
    multi:true,
    style: styleFunction
});

**Comment by walkermatt** [comment]
If you only want to include features from visible layers then check the layer visibility before adding them to the `selectedFeature` collection.

```
if (select_layer.getVisible()) {
    // Add to the collection
}
```

**Comment by homeandr777** [comment]
I find the the way to uploads the pictures. Just for example I have done pictures somewhere on Openstreetmap.

The checking with your methode working but now, there is another Problem.
overlayGroup.getProperties().layers.array_[3].values_.visible
I want to write a methode to get everytime the right layer to be checked, now I have not any idea how can I do it (write such a function). But this is another Problem.

![notselected](https://cloud.githubusercontent.com/assets/21321724/18203419/57304da6-7117-11e6-9354-8e7c85979e33.jpg)

![selectedfeaturesyellow](https://cloud.githubusercontent.com/assets/21321724/18203421/57348560-7117-11e6-91a1-dce1c668f7a2.jpg)

You see the selected features, and deselected layer, after deselection, selected features stayed. When I do a new selection it's gone away, because now I am tested, what you write me.  
On every new selection I am Cleaning everything, with clear() methode.

![layersnotselected](https://cloud.githubusercontent.com/assets/21321724/18203420/5733445c-7117-11e6-9478-c9a9b8aa9ed1.jpg)

So my question is are there any events, with the Checkbox selections?
That I can use to do my Stuff?

Thank you very much

**Comment by walkermatt** [comment]
Each layer dispatches a `change:visible` event when it's visibility changes, see: https://github.com/walkermatt/ol3-layerswitcher/issues/30#issuecomment-190136675
