### ISSUE TITLE
Compatibility to OpenLayers 4

### ISSUE THREAD

**Issue by danieltulp** [walkermatt/ol3-layerswitcher#52]
Is this compatible to OpenLayers 4? Possibly it is, so check it out. https://github.com/openlayers/openlayers/releases/tag/v4.0.1

**Comment by walkermatt** [comment]
Hi, yes I full expect compatibility with ol4, see [the v4.0.0 release notes](https://github.com/openlayers/openlayers/releases/tag/v4.0.0) for details of the new version scheme.

I'm considering renaming ol3-layerswitcher and ol3-popup to ol-layerswitcher and ol-popup and providing support for both [OpenLayers as ES2015 modules](https://www.npmjs.com/package/ol/) as well as `require` and the current global.

**Comment by fredj** [comment]
@walkermatt when renaming the projects to ol-*, don't forget to update this page:
http://openlayers.org/3rd-party/

(https://github.com/openlayers/openlayers.github.io/blob/build/src/pages/3rd-party/index.hbs)
