### ISSUE TITLE
Get selected layer group title

### ISSUE THREAD

**Issue by nformica** [walkermatt/ol3-layerswitcher#53]
Referring to issue #30 (Add listener on selected layer) , how can I get group "title" of selected layer ?

Regards
Nino

**Comment by walkermatt** [comment]
I don't think that OpenLayers `ol.layer.Layer` instances provides a reference to the parent group so I think you'd have to maintain information about the relationship yourself. Try something like this:

    // Add a 'parent' property of each child layer which is a reference to the
    // ol.Layer.Group that it belongs to
    function addParent(parentLyr) {
        parentLyr.getLayers().forEach(function(lyr, idx, a) {
            lyr.set('parent', parentLyr);
            if (lyr.getLayers) {
                addParent(lyr);
            }
        });
    }

    addParent(map.getLayerGroup());

    ol.control.LayerSwitcher.forEachRecursive(map, function(l, idx, a) {
        l.on("change:visible", function(e) {
            var lyr = e.target;
            console.log(lyr.get('title'), lyr.getVisible(), 'Parent: ' + lyr.get('parent').get('title'));
        });
    });

**Comment by nformica** [comment]
Wonderful ... it works!

many thanks
Nino

2017-03-02 17:55 GMT+01:00 Matt Walker <notifications@github.com>:
