### ISSUE TITLE
Safari not working

### ISSUE THREAD

**Issue by livadiotis** [walkermatt/ol3-layerswitcher#54]
the layerswitcher does not work in safari. 
The radio button (basemaps) as also the layer selection (check box) can not be changed when the map is accessed using safari browser
I do not own an OS device to locate the error

**Comment by walkermatt** [comment]
Hi, can you provide some more detail such as:

* which version of Safari?
* on desktop, phone or tablet?
* which OS?
* what's the URL are you seeing the issue with?
* can you provide a screenshot?

**Comment by livadiotis** [comment]
Since i do not own an OS device i tested it with friends OS phones (iphone6) and MacBook.
It seems not to be working only on iphones (Safari). It worked with MacBook (Safari)
the website is http://maps.palsurveying.com
The demo versions that you have on github work with iphones as also with Macbook.
So i guess somewhere my code  breaks the layerswitcher only in iphones.
I would do further testing to locate the error
Consider that this error as resolved as its not  layerswitcher fault
Thank you

**Comment by walkermatt** [comment]
Thanks for testing, I'll close this for now but feel free to add any further info if you uncover anything 👍
