### ISSUE TITLE
WMS GetFeatureInfo (Tile Layer) in Layerswitcher still ON even after unchecking layer in switcher

### ISSUE THREAD

**Issue by TOMASSTA** [walkermatt/ol3-layerswitcher#55]
Hi Matt, 

first of all, thanks a lot for this great LayerSwitcher ! 
Also, sorry for my english, not my mother tongue...
Last, I'my js skills are VERY limited as I started a few month ago. 

I'm loading a wms layer in my project, and I trigger WMS GetFeatureInfo requests on click events (in a popup). It works, but when I uncheck the layer in the swicther, it still triggers the GetFeatureInfo, and opens the popup...

I think I have to add an "if LAYER-X in layerswitcher is ON then..." somewhere, but how can I check if a layer is checked in the layerswitcher? 

Thanks again,

**Comment by walkermatt** [comment]
Hi, looks like you might of found a solution but in case others have the same question I'd suggest checking the visibility of each layer before getting info via [`ol.layer.Base#getVisible`](https://openlayers.org/en/latest/apidoc/ol.layer.Base.html#getVisible).

**Comment by TOMASSTA** [comment]
Hi Matt, 
this is exactly what I've done. 
Thx
