### ISSUE TITLE
Tooltip on layer hover in the layerswitcher

### ISSUE THREAD

**Issue by TOMASSTA** [walkermatt/ol3-layerswitcher#57]
Hi Matt, 

is there a way to ad a tooltip on mouse hover in your layerswitcher (like in this page)? 

http://sigeom.mines.gouv.qc.ca/signet/classes/I1108_afchCarteIntr#

regards, 

Tom

**Comment by walkermatt** [comment]
Hi, no the layerswitcher doesn't provide support for that sort of tooltip with info about a layer. You might be able to implement it yourself by adding appropriate handlers to the `label` elements but I don't expect adding this functionality to the layerswitcher itself ATM.
