### ISSUE TITLE
Exclusive overlay layers

### ISSUE THREAD

**Issue by geraldo** [walkermatt/ol3-layerswitcher#65]
I have overlay layers which need to be mutually exclusives, additionally to some base layers. 

There is a [solution](https://gis.stackexchange.com/questions/60733/how-to-make-the-overlays-in-openlayers-exclusives-using-events-at-checkbox-level#61020) for plain Openlayers, but I can't get it to work using ol3-layerswitcher.

I also tried setting layer.setVisible(false) to false after a "change:visible" event gets triggered. The problem is that this event gets propagated and on the second run all layers get invisible. I did something like that:

```
ol.control.LayerSwitcher.forEachRecursive(map, function(l, idx, a) {
  l.on("change:visible", function(e, react) {

    exclusiveOverlays.forEach(function(layer, i) {
      if (e.target.get('title') !== layer.getProperties().title) {
        layer.setVisible(false);
      }
    });
  });
});
```

**Comment by walkermatt** [comment]
@geraldo while not supported within the layerswitcher itself. The following based on your code above should do the trick

    // NOTE exclusiveOverlays is an Array of ol.Layer

    ol.control.LayerSwitcher.forEachRecursive(map, function(l, idx, a) {
        l.on("change:visible", function(e, react) {
            if (e.target.getVisible()) {
                enforceExclusive(exclusiveOverlays, e.target);
            }
            layerSwitcher.renderPanel();
        });
    });

    function enforceExclusive (layers, visibleLayer) {
        layers.forEach(function(layer, i) {
            if (visibleLayer !== layer) {
                layer.setVisible(false);
            }
        });
    }

    // Ensure we enforce exclusive display initially
    enforceExclusive(exclusiveOverlays, exclusiveOverlays[0]);

**Comment by geraldo** [comment]
Thanks @walkermatt, that saved my day! 

Only a note for people adding this code: On defining the layer, layer option visible has to be set to true (as default) to make exclusiveOverlays[0] initially visible.
